help :-
    gameStarted,
    write(' 1. status     : untuk menampilkan kondisi terkini'), nl,
    write(' 2. map        : untuk menampilkan peta'), nl,
    write(' 3. inventory  : untuk menyimpan barang dan equipments tidak terpakai'), nl,
    write(' 4. throwItem  : untuk membuang barang dan equipments tidak terpakai'), nl,
    write(' 5. quest      : untuk mendapatkan misi baru'), nl,
    write(' 6. a          : untuk bergerak 1 langkah ke barat'), nl,
    write(' 7. s          : untuk bergerak 1 langkah ke selatan'), nl,
    write(' 8. w          : untuk bergerak 1 langkah ke utara'), nl,
    write(' 9. d          : untuk bergerak 1 langkah ke timur'), nl,
    write('10. dig        : untuk menggali tile'), nl,
    write('11. plant      : untuk menanam seed'), nl,
    write('12. harvest    : untuk memanen tanaman'), nl,
    write('13. fish       : untuk mendapatkan ikan'), nl,
    write('14. ranch      : untuk melihat list hewan ternak beserta jumlahnya'), nl,
    write('15. market     : untuk masuk ke dalam market'), nl,
    write('16. buy        : untuk membeli barang'), nl,
    write('17. sell       : untuk menjual barang'), nl,
    write('18. exitShop   : untuk keluar dari market'), nl,
    write('19. house      : untuk masuk ke dalam house'), nl,
    write('20. sleep      : untuk tidur'), nl,
    write('21. writeDiary : untuk menulis diary'), nl,
    write('22. readDiary  : untuk membaca diary'), nl,
    write('23. exitHouse  : untuk keluar dari house'), nl,
    write('24. help       : untuk menampilkan segala bantuan'), nl,
    write('25. exit       : untuk mengakhiri petualangan'), nl.