startGame :-
    \+ gameStarteda,
    assertz(gameStarteda),
    write(''), nl,
    write('[]****************************************************************[]'), nl,
    write('||   __   __                                             __       ||'), nl,
    write('||  |  | |  |   ___ ___   __ ______      ______     ____|  |      ||'), nl,
    write('||  |  |_|  | /   __`  | |   ___\\  \\    /  /   \\   /    |  |____  ||'), nl,
    write('||  |   _   | |  /  |  | |  |    \\  \\  /  /  __ \\ /  ___|   ____| ||'), nl,
    write('||  |  | |  | |  |__|  | |  |     \\  \\/  /   ___/ \\____ \\  |____  ||'), nl,
    write('||  |__| |__|  \\ _ __ _| |__|      \\____/ \\_____| |_____/ \\_____| ||'), nl,
    write('||                                                                ||'), nl,
    write('[]****************************************************************[]'), nl,
    write(''), nl,
    write('Harvest Star!!!'),nl,
    write(''), nl,
    write('Let''s play and pay our debts together!'), nl,
    write(''), nl,
    write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'), nl,
    write('%                      ~Harvest Star~                         %'), nl,
    write('% 1. start    : untuk memulai petualangan                     %'), nl,
    write('% 2. exitGame : untuk keluar dari game                        %'), nl,
    write('%                                                             %'), nl,
    write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'), nl.